exports.transport_controller = require('./transport_controller')
exports.adminController = require('./adminController')
exports.wisata_controller = require('./wisata_controller')
exports.hotel_controller = require('./hotel_controller')
exports.auth_controller = require('./auth_controller')
exports.transaksi_controller = require('./transaksi_controller')